export const TOOL_ITEMS = {
  BRUSH: "BRUSH",
  LINE: "LINE",
  RECTANGLE: "RECTANGLE",
  ELLIPSE: "ELLIPSE",
  DRAG: "DRAG",
  ARROW: "ARROW",
  ERASER: "ERASER",
};

export const TOOL_ACTION_TYPE = {
  NONE: "NONE",
  DRAWING: "DRAWING",
  DRAGGING: "DRAGGING",
  ERASING: "ERASING",
};

export const COLORS = {
  WHITE: "#ffffff",
  RED: "#ff0000",
  GREEN: "#00ff00",
  BLUE: "#0000ff",
  ORANGE: "#ffa500",
  YELLOW: "#ffff00",
  BLACK: "#000000",
};
export const SIDE_BAR_ACTION = {
  CHANGE_STROKE: "CHANGE_STROKE",
  CHANGE_FILL: "CHANGE_FILL",
  CHANGE_SIZE: "CHANGE_SIZE",
};

export const FILL_TOOL_TYPES = [TOOL_ITEMS.RECTANGLE, TOOL_ITEMS.ELLIPSE];
export const STROKE_TOOL_TYPES = [
  TOOL_ITEMS.BRUSH,
  TOOL_ITEMS.RECTANGLE,
  TOOL_ITEMS.ARROW,
  TOOL_ITEMS.LINE,
  TOOL_ITEMS.ELLIPSE,
];
export const SIZE_TOOL_TYPES = [
  TOOL_ITEMS.RECTANGLE,
  TOOL_ITEMS.ARROW,
  TOOL_ITEMS.LINE,
  TOOL_ITEMS.ELLIPSE,
];
export const ELEMENT_ERASE_THRESHOLD = { LINE: 1, RECTANGLE: 2 };
